
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1048x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1048,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    133.0,
    446.0,
    anchor="nw",
    text="If you already have an account ",
    fill="#000000",
    font=("Poppins Regular", 16 * -1)
)

canvas.create_text(
    133.0,
    472.0,
    anchor="nw",
    text="You can   Login here !",
    fill="#000000",
    font=("Poppins Regular", 16 * -1)
)

canvas.create_text(
    129.0,
    284.0,
    anchor="nw",
    text="Sign Up to ",
    fill="#000000",
    font=("Poppins SemiBold", 50 * -1)
)

canvas.create_text(
    129.0,
    354.0,
    anchor="nw",
    text="Waddy",
    fill="#000000",
    font=("Poppins Medium", 35 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    735.5,
    223.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFEFFF",
    highlightthickness=0
)
entry_1.place(
    x=539.0,
    y=202.0,
    width=393.0,
    height=41.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=531.0,
    y=555.0,
    width=409.0,
    height=42.0
)

canvas.create_text(
    52.0,
    42.0,
    anchor="nw",
    text="Waddy",
    fill="#000000",
    font=("Poppins SemiBold", 20 * -1)
)

canvas.create_text(
    541.0,
    181.0,
    anchor="nw",
    text="First Name",
    fill="#A7A2FF",
    font=("Poppins Regular", 15 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    735.5,
    292.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EFEFFF",
    highlightthickness=0
)
entry_2.place(
    x=539.0,
    y=270.0,
    width=393.0,
    height=42.0
)

canvas.create_text(
    541.0,
    249.0,
    anchor="nw",
    text="Last Name",
    fill="#A7A2FF",
    font=("Poppins Regular", 15 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    735.5,
    359.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#EFEFFF",
    highlightthickness=0
)
entry_3.place(
    x=539.0,
    y=337.0,
    width=393.0,
    height=42.0
)

canvas.create_text(
    541.0,
    317.0,
    anchor="nw",
    text="Email",
    fill="#A7A2FF",
    font=("Poppins Regular", 15 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    735.5,
    427.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#EFEFFF",
    highlightthickness=0
)
entry_4.place(
    x=539.0,
    y=406.0,
    width=393.0,
    height=41.0
)

canvas.create_text(
    541.0,
    385.0,
    anchor="nw",
    text="Password",
    fill="#A7A2FF",
    font=("Poppins Regular", 15 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    735.5,
    495.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#EFEFFF",
    highlightthickness=0
)
entry_5.place(
    x=539.0,
    y=473.0,
    width=393.0,
    height=43.0
)

canvas.create_text(
    541.0,
    453.0,
    anchor="nw",
    text="Telephone Number",
    fill="#A7A2FF",
    font=("Poppins Regular", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
